### ISSUE TITLE
Add support for SCRAM-SHA-256 authentication

### ISSUE THREAD

**Issue by ngalantowicz** [newrelic/nri-mongodb#67]
## Is your feature request related to a problem? Please describe.
Integration fails due to no mongo 4+ SCRAM-SHA-256 authentication support.  I've found that the driver you all use has yet to enable support for SCRAM-SHA-256 authentication as well.  There's an existing [pr](https://github.com/globalsign/mgo/pull/282) (stale - 2+ years old) in the driver repo you all use.  I understand that this will need to be done first in order to enable here, so I'm curious and asking if the mgo feature is completed would you all be willing to support it.

## Feature Description
Enable mongo 4+ SCRAM-SHA-256 authentication mechanism

## Describe Alternatives
n/a

## Additional context
Existing mgo [pr](https://github.com/globalsign/mgo/pull/282) seeking support for completion

## Priority
Blocker

**Comment by ngalantowicz** [comment]
My bad I didn't mean to close got a little trigger happy :)

**Comment by gsanchezgavier** [comment]
Hi @ngalantowicz , this really looks interesting i have tagged this issue to be prioritized by our PM.

**Comment by roobre** [comment]
Hi,

We are currently using the [`mgo`](https://github.com/globalsign/mgo) driver which, to our knowledge, is now kind of in a "maintenance mode", and it's hard to get new features added to it, so I wouldn't be too optimistic regarding that PR getting merged.

We have talked a couple times about migrating to the official mongo driver, and this could be something to weight in for that. Are you aware if the official driver supports SCRAM?

**Comment by ngalantowicz** [comment]
@gsanchezgavier and @roobre thanks for taking an interest in this feature.

The official mongo driver does support SCRAM

https://github.com/mongodb/mongo-go-driver/blob/master/mongo/options/clientoptions.go#L45-#L46

**Comment by roobre** [comment]
@ngalantowicz Thanks for the confirmation! We'll add this to the list of things to track for the migration :)

**Comment by Neustradamus** [comment]
@ all: I wish you a Happy New Year 2022!

Any news about it?

**Comment by pyrotechnics-io** [comment]
Incidentally, I'm working on a fork which essentially removes globalsign/mgo in favour of the mongodb official driver here : https://github.com/pyrotechnics-io/nri-mongodb. This would at least in theory allow it to be used for SCRAM-SHA-256 as well as MongoDB 5 (has undergone some very basic testing against 4.4 with SCRAM-SHA-256). The approach followed is to mimick the interface of mgo as used in the code with a facade wrapper and then eventually refactor and do away with the wrapper altogether. A lot of the test code had deep hooks into mgo objects unfortunately so had to temporarily disable several of them.

**Disclaimer**: Its still a pre-alpha wip but any help testing it is much appreciated.

**Comment by pyrotechnics-io** [comment]
Just fyi but if testing is validated, the fork above in theory should address #67, #70, #71, #76, #78

**Comment by mangulonr** [comment]
Hi

The [new MongoDB OHI](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new/) has been released in public preview, this version will be GA during June.

**Some of the new features provided:**

- Compatibility with [MongoDB Atlas](https://www.mongodb.com/cloud/atlas/efficiency).
- Support of the latest major MongoDB versions 5 and 6.
- Compatibility with [Percona Server for MongoDB](https://www.percona.com/software/mongodb/percona-server-for-mongodb).
- Support of SCRAM authentication.
- Integration with the [entity explorer](https://one.newrelic.com/nr1-core) thanks to 3 new entity types (MongoDB instance, database, and collection).
- Improved new [MongoDB quickstart](https://newrelic.com/instant-observability/mongodb-prometheus).
- Improved [metrics filtering capabilities](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new/#instance-settings).

For more information check the following resources.

- [Documentation](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new/)
- [Migration guide](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-migration-guide/)
- [Quickstart](https://newrelic.com/instant-observability/mongodb-prometheus)

Because it is based on Prometheus the metric names are different from our [legacy](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration/) OHI, check our [migration guide](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-migration-guide/) if you need more details.
Our [legacy](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration/) MongoDB OHI will be deprecated on FY24H2 (final date pending to be decided).
