### ISSUE TITLE
Move to the official mongodb client

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/nri-mongodb#71]
Currently we are using a third party mongodb library , we could move to the official one https://github.com/mongodb/mongo-go-driver

**Comment by paologallinaharbur** [comment]
The library we are using is deprecated

**Comment by mangulonr** [comment]
Hi

The [new MongoDB OHI](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new/) has been released in public preview, this version will be GA during June.

**Some of the new features provided:**

- Compatibility with [MongoDB Atlas](https://www.mongodb.com/cloud/atlas/efficiency).
- Support of the latest major MongoDB versions 5 and 6.
- Compatibility with [Percona Server for MongoDB](https://www.percona.com/software/mongodb/percona-server-for-mongodb).
- Support of SCRAM authentication.
- Integration with the [entity explorer](https://one.newrelic.com/nr1-core) thanks to 3 new entity types (MongoDB instance, database, and collection).
- Improved new [MongoDB quickstart](https://newrelic.com/instant-observability/mongodb-prometheus).
- Improved [metrics filtering capabilities](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new/#instance-settings).

For more information check the following resources.

- [Documentation](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new/)
- [Migration guide](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-migration-guide/)
- [Quickstart](https://newrelic.com/instant-observability/mongodb-prometheus)

Because it is based on Prometheus the metric names are different from our [legacy](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration/) OHI, check our [migration guide](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-migration-guide/) if you need more details.
Our [legacy](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration/) MongoDB OHI will be deprecated on FY24H2 (final date pending to be decided).
